### ISSUE TITLE
Getting Referenced sniff "WordPress.NamingConventions.PrefixAllGlobals" does not exist error when creating custom ruleset

### ISSUE THREAD

**Issue by dingo-d** [WordPress-Coding-Standards/WordPress-Coding-Standards#1018]
I am writing a custom ruleset for a company I'm working for, and I hit a snag.

In a folder called `Infinum` I placed folder `Sniffs` (which I'll probably need to fill with some custom sniffs) and `ruleset.xml` which looks like this:

```xml
<?xml version="1.0"?>
<ruleset name="Infinum">
  <description>Infinum custom coding standards</description>

  <!-- Load WordPress Coding standards - these include Extra, Core and VIP -->
  <rule ref="WordPress"/>

  <!-- Exclude node and composer folders -->
  <exclude-pattern>vendor/*</exclude-pattern>
  <exclude-pattern>node_modules/*</exclude-pattern>
  <exclude-pattern>*/data/*</exclude-pattern>

  <!-- Only check php code, linters are checking js and css -->
  <arg name="extensions" value="php"/>

  <!-- Define default report type -->
  <arg name="report" value="summary"/>

  <!-- Enable colors in report -->
  <arg name="colors"/>

  <!-- We work with modified VIP standard -->
  <rule ref="WordPress-VIP">
    <exclude name="WordPress.VIP.FileSystemWritesDisallow" />
    <exclude name="WordPress.VIP.RestrictedFunctions" />
    <exclude name="WordPress.VIP.RestrictedVariables" />
    <exclude name="WordPress.VIP.SuperGlobalInputUsage" />
    <exclude name="WordPress.VIP.DirectDatabaseQuery" />
    <exclude name="WordPress.PHP.YodaConditions" />
  </rule>

  <!-- Disable check for translators comments -->
  <rule ref="WordPress">
    <exclude name="WordPress.WP.I18n.TranslatorsCommentWrongStyle" />
    <exclude name="WordPress.WP.I18n.MissingTranslatorsComment" />
  </rule>

  <!-- Add check for default prefix -->
  <rule ref="WordPress.NamingConventions.PrefixAllGlobals">
    <properties>
      <property name="prefixes" type="array" value="inf" />
    </properties>
  </rule>

  <!-- Set minimum supported version for deprecated functions -->
  <rule ref="WordPress.WP.DeprecatedFunctions">
    <properties>
      <property name="minimum_supported_version" value="4.4" />
    </properties>
  </rule>

  <!-- Allow theme hierarchy specific file name exceptions -->
  <rule ref="WordPress.Files.FileName">
    <properties>
      <property name="is_theme" value="true" />
    </properties>
  </rule>

  <!-- Forbidden space after function keyword and open parenthesis -->
  <rule ref="WordPress.WhiteSpace.ControlStructureSpacing">
    <properties>
      <property name="spaces_before_closure_open_paren" value="0" />
      <property name="blank_line_check" value="true" />
    </properties>
  </rule>

  <!-- File Layout: Classes in own file. -->
  <rule ref="PSR1.Classes.ClassDeclaration" />

</ruleset>
```

Now, when I try to sniff a file for test I get

```
Fatal error: Uncaught exception 'PHP_CodeSniffer_Exception' with message 'Referenced sniff "WordPress.NamingConventions.PrefixAllGlobals" does not exist' in /Users/infinum/wpcs/vendor/squizlabs/php_codesniffer/CodeSniffer.php:1167
Stack trace:
#0 /Users/infinum/wpcs/vendor/squizlabs/php_codesniffer/CodeSniffer.php(780): PHP_CodeSniffer->_expandRulesetReference(Object(SimpleXMLElement), '/Users/infinum/...', 0)
#1 /Users/infinum/wpcs/vendor/squizlabs/php_codesniffer/CodeSniffer.php(578): PHP_CodeSniffer->processRuleset('/Users/infinum/...')
#2 /Users/infinum/wpcs/vendor/squizlabs/php_codesniffer/CodeSniffer/CLI.php(956): PHP_CodeSniffer->initStandard(Array, Array, Array)
#3 /Users/infinum/wpcs/vendor/squizlabs/php_codesniffer/CodeSniffer/CLI.php(113): PHP_CodeSniffer_CLI->process()
#4 /Users/infinum/wpcs/vendor/squizlabs/php_codesniffer/scripts/phpcs(25): PHP_CodeSniffer_CLI->runphpcs()
#5 {main}
  thrown in /Users/infinum/wpcs/vendor/squizlabs/php_codesniffer/CodeSniffer.php on line 1167
```

I followed the [Customizable sniff properties](https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/wiki/Customizable-sniff-properties), so this should be ok. What am I doing wrong?

**Comment by GaryJones** [comment]
Sounds like you are using PHP_CodeSniffer 3. 

WPCS is only compatible with PHP_CodeSniffer 2.9.* for now.

**Comment by dingo-d** [comment]
Nope, I'm using 2.9.1 version. When I comment

```xml
<!-- Add check for default prefix -->
  <rule ref="WordPress.NamingConventions.PrefixAllGlobals">
    <properties>
      <property name="prefixes" type="array" value="inf" />
    </properties>
  </rule>
```

The sniff works

**Comment by jrfnl** [comment]
Actually, sounds like you are using WPCS `master`, i.e. the 0.11.0 version, while that sniff was only added in WPCS 0.12.0 which has not been released yet, i.e. the `develop` branch.

How are you pulling in WPCS ? If via Git, switch the branch to `develop` to fix this.

**Comment by dingo-d** [comment]
I installed it via composer or PEAR (it was a little while ago), and it is version 0.11.0. If that's the case I'll just comment it out for now. 

Thanks for clearing it up.

**Comment by danielbachhuber** [comment]
For the next time I run into this, the solution was to run:

```
phpcs --config-set installed_paths /Users/danielbachhuber/.composer/global/wp-coding-standards/wpcs/vendor/wp-coding-standards/wpcs
````

Update the path to your appropriate path. If, for some reason, Composer didn't correctly run the post-install-cmd, the error you end up with is pretty cryptic.

**Comment by jrfnl** [comment]
@danielbachhuber That is the solution for another problem and another error - one where the WordPress rulesets cannot be found.
This issue is specifically about one particular sniff not being found which is referenced in a custom ruleset, but doesn't exists (yet) in the version of WPCS which was installed.
