### ISSUE TITLE
Get a PHP_CodeSniffer_Exception when defining the wpcs ruleset.xml via phpcs.xml

### ISSUE THREAD

**Issue by rpkoller** [WordPress-Coding-Standards/WordPress-Coding-Standards#537]
I've done the standalone installation of wp coding standards via git. i am running sublime text 3 with sublimelinter and sublimelinter-phpcs. inside a test directory i've included a front-page.php file from one of my wordpress installations and the phpcs.xml file. i wanted to define the standards on a per project basis so i am able to lint wordpress as well as e.g. drupal projects. the phpcs.xml file looks like: 

```
<?xml version="1.0"?>
<ruleset name="phpcs test">
 <description>phpcs test for wordpress</description>
 <rule ref="/users/myuser/.codesniffer/wpcs/WordPress-Core/ruleset.xml"/>
</ruleset>
```
if i go into the terminal and just run `phpcs front-page.php`i get the following error then: 
```
Fatal error: Uncaught exception 'PHP_CodeSniffer_Exception' with message 'Referenced sniff "WordPress.Arrays.ArrayDeclaration" does not exist' in phar:///Users/myuser/.codesniffer/bin/phpcs/CodeSniffer.php:1121
Stack trace:
#0 phar:///Users/myuser/.codesniffer/bin/phpcs/CodeSniffer.php(734): PHP_CodeSniffer->_expandRulesetReference(Object(SimpleXMLElement), '/users/myuser/....', 2)
#1 phar:///Users/myuser/.codesniffer/bin/phpcs/CodeSniffer.php(1134): PHP_CodeSniffer->processRuleset(Object(SimpleXMLElement), 2)
#2 phar:///Users/myuser/.codesniffer/bin/phpcs/CodeSniffer.php(734): PHP_CodeSniffer->_expandRulesetReference(Object(SimpleXMLElement), '/Users/myuser/D...', 0)
#3 phar:///Users/myuser/.codesniffer/bin/phpcs/CodeSniffer.php(551): PHP_CodeSniffer->processRuleset('/Users/myuser/D...')
#4 phar:///Users/myuser/.codesniffer/bin/phpcs/CodeSniffer/CLI.php(844): PHP_CodeSniffer->initStandard(Array, Array)
#5 phar:///Users/myuser/.codesniffer/bin/phpcs/CodeSniffer/CLI.php(104): PHP_CodeSniffer_CLI->process()
#6 /Users/myuser in phar:///Users/myuser/.codesniffer/bin/phpcs/CodeSniffer.php on line 1121
```
Is that a wpcs ruleset issue or shall i report it upstream on the codesniffer repo? best regards r.

**Comment by westonruter** [comment]
You're not referring to a ruleset properly. You need to install WPCS as a standard for PHP_CodeSniffer (adding your `wpcs` directory to the PHPCS paths), and then all you need to do is:

```xml
<rule ref="WordPress-Core"/>
```
